language: node_js
node_js:
- 6
- 5
- 4
- 0.12
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_success: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
env:
  global:
  - secure: AWA35sijfpQjvaNZVRrDJlR+uakBOh7lSzetCDkSlIt+VG4RvC85JAtqwCniGGICNURgxuadt1v3KgNlcHsE9LYgOjSysSypyPqnRCw9k1QZRe0IwhT7RG1nnFPC3yuAtIM5v7+OC2d63qmSbiYIgAc+dfwLKhH7be/8pAYnP5uBN9bGyVj6PAezqbNPYQuCUYy6JhoMawMViyEH5D1Gqd5hAQeXmMCxIunUXsUMDZb4Fs5nZHqTWBJsDudof6drKVe9Ya3w6He17rLKyCzk2pQCLfMH7CuacRWNDG52ED+ljLopqrv25pm1YhAYSOAusTwDxWLwRdzowgVWaWQ6XDSyVZl3fSsNMjWuCVL12sMVxyNcyRmNSr+oHJ+DYWBfheNCyTlmzdyetlHoonNVyzFLj7O2jLX6Y0rLpvHFyrbMkSYeiT54R03w44EDQZF5huIrMmxhhQnXMevBmWfqy0PWXyJMxXUidupw/xWN+xZFOXwfOiScBsBGoukjL+4Uay6d9heHPQ3dv7kME0FtvUm0BQtYMUm8UtNd92QWCzfPyVgZ9EQzsNAn7ABzdeDBep4zStMg95qimYPVt0VtoxoGavO/LcLMABpxYR20cT3L6NDSBAVxO7pUBOVNv60V9zYyS4jF+iiM2fIY0di2/6dH4k207/IillAoGMH3LaU=
  - secure: HrQqR702Xgtfl0i1JECrK6I+eFKxiKmfJe8uJqQqFAL6ZntoomsfH7tpqW/4MZgdWEEpPLeJJK3zv2HEjsGwqpFhqKZS0918K+u0QeaTrrdc0eFkB1ReA1rjDnALQY1OqF0IrjpOf7CVW83GddKDWtKeI79vvp9Ds/zVRDwWdpD9XQ7SOohGdKSOI7RGJKy1DzvNXTxWWVyvDeFugs9zwcvbeBP7KBpKLt6pjRVr6QYlDvyWukG2pQf1RF51UfecBvYX6KNys7AiiJ+IlkQ0WnZ13j9Nu/g4JTJ/FZJOYSlauJvRCvOxOG/i+5PRtGe3iYzN58tc6hRHrQuHO0MvOsQ/7NR1lQn52uEI1lfVas41uVCjwu6gvYQmMhXEnoGGv1vYW8X6uLozAA01sOwXsXhFTvMWqtuYNmhw/W3bDZkQkNfUX99oeBB0dPaErUaK3U0HqCyRtlVA3C4VVPU9Ids+As1u3h9RnFJBSDqKRyC0O/zBJiJDsLvjraQYMVxQ3ZZqMjTWDkdNKQ8i3PnbefQ326iRRFfQHiWws0/NoLdzUFebqnWmM0t7PyCQzp30DF1TQTMEALsQt/meZQ/FauSAvBsgY1JF9og2tJM4iuJiw9esqrOcGvbnjST5eR6iAzm7loRLuD2qfVXCJEvWLt/5F46MTOK3d/aWft5Z8hY=
