language: node_js
node_js:
- 6
- 5
- 4
- 0.12
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_success: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
env:
  global:
  - secure: AWA35sijfpQjvaNZVRrDJlR+uakBOh7lSzetCDkSlIt+VG4RvC85JAtqwCniGGICNURgxuadt1v3KgNlcHsE9LYgOjSysSypyPqnRCw9k1QZRe0IwhT7RG1nnFPC3yuAtIM5v7+OC2d63qmSbiYIgAc+dfwLKhH7be/8pAYnP5uBN9bGyVj6PAezqbNPYQuCUYy6JhoMawMViyEH5D1Gqd5hAQeXmMCxIunUXsUMDZb4Fs5nZHqTWBJsDudof6drKVe9Ya3w6He17rLKyCzk2pQCLfMH7CuacRWNDG52ED+ljLopqrv25pm1YhAYSOAusTwDxWLwRdzowgVWaWQ6XDSyVZl3fSsNMjWuCVL12sMVxyNcyRmNSr+oHJ+DYWBfheNCyTlmzdyetlHoonNVyzFLj7O2jLX6Y0rLpvHFyrbMkSYeiT54R03w44EDQZF5huIrMmxhhQnXMevBmWfqy0PWXyJMxXUidupw/xWN+xZFOXwfOiScBsBGoukjL+4Uay6d9heHPQ3dv7kME0FtvUm0BQtYMUm8UtNd92QWCzfPyVgZ9EQzsNAn7ABzdeDBep4zStMg95qimYPVt0VtoxoGavO/LcLMABpxYR20cT3L6NDSBAVxO7pUBOVNv60V9zYyS4jF+iiM2fIY0di2/6dH4k207/IillAoGMH3LaU=
  - secure: HrQqR702Xgtfl0i1JECrK6I+eFKxiKmfJe8uJqQqFAL6ZntoomsfH7tpqW/4MZgdWEEpPLeJJK3zv2HEjsGwqpFhqKZS0918K+u0QeaTrrdc0eFkB1ReA1rjDnALQY1OqF0IrjpOf7CVW83GddKDWtKeI79vvp9Ds/zVRDwWdpD9XQ7SOohGdKSOI7RGJKy1DzvNXTxWWVyvDeFugs9zwcvbeBP7KBpKLt6pjRVr6QYlDvyWukG2pQf1RF51UfecBvYX6KNys7AiiJ+IlkQ0WnZ13j9Nu/g4JTJ/FZJOYSlauJvRCvOxOG/i+5PRtGe3iYzN58tc6hRHrQuHO0MvOsQ/7NR1lQn52uEI1lfVas41uVCjwu6gvYQmMhXEnoGGv1vYW8X6uLozAA01sOwXsXhFTvMWqtuYNmhw/W3bDZkQkNfUX99oeBB0dPaErUaK3U0HqCyRtlVA3C4VVPU9Ids+As1u3h9RnFJBSDqKRyC0O/zBJiJDsLvjraQYMVxQ3ZZqMjTWDkdNKQ8i3PnbefQ326iRRFfQHiWws0/NoLdzUFebqnWmM0t7PyCQzp30DF1TQTMEALsQt/meZQ/FauSAvBsgY1JF9og2tJM4iuJiw9esqrOcGvbnjST5eR6iAzm7loRLuD2qfVXCJEvWLt/5F46MTOK3d/aWft5Z8hY=
deploy:
  provider: npm
  email: as.us.awscto@sungardas.com
  api_key:
    secure: RE+RQROZw24sVo0SCI5aZ8Kn+usiKrcG4aTn7jlqsDjg/fHAMtTBONr6pQitTbuZ3a8PioqhGlVDz9Q6fYUFT0GAyBR23IKbR+FG1IZfHX64pHUaOlNqr7o9WidOFdcRfKMJkbywZ1S9TY2xwGktFV8OvLVjcsE/svZrFNEct6LDKVrJ1PTgsds+44MmBjWdk/CNwWMzckDmxRv+4051p2CjBA2BwmobrAOHKUlM4VNc480Z4j6FdYK5lyrp3h32Ts1BVubVXds2XQ/2AfSk0YLwlcjqTefsVsFan/M2PVaYKjuuYI/UNm2pxSmCNkw43ASGjv+2AEFp+cvJ19tXMwszvh/QwapB61L6/q42CyR/iY4K86OhpM+DfrHkxtfVvHzIwY0ufWxKsf5Mj+Bpf4fWZcT1pyS6PT6oIKJJLO2CxA5xGY5D3mH/pMuSfpiu6f9+rrc5tX1uZfq8hFG+uGgnPpIJpA4Aybms76BaqHYXXqbyBE7j/WEtupn8Pi3Tq3e1R+frJXkTfcm4g72CS6HFfnDnCC95OGycbGVvFYTdfNbyz1TLAb43ahZC8uXBv+RGq15PumCDlGsth9TwjZCHoPaejtDlbtORLVqC6Oe4ha/2QtGJqQGLlwI1wXYm+10semrMtiM26QaT7/yxC+YMzuNjkwFTQNvPXazFHzg=
  on:
    tags: true
    repo: SungardAS/particles-spotinst
    node: 6
